### PR TITLE
feat: add new grey color theme

### PR DESCRIPTION
**Pull request by chadhamre**
I really love your theme. I just wanted to create one variation that had a little less contrast to be softer on the eyes.

### CODE REVIEW

**Comment by maoma87** [comment]
Awesome @chadhamre thanks for the contribution, right now I'm on vacation I'll look at this as soon as I come back, thanks again

**Comment by chadhamre** [comment]
one thing I forget to mention, is that I tried to make this theme similar to the `atom-one-dark` as it is a very popular theme.
Screen Shot 2019-08-08 at 11 22 45 AM

**Comment by maoma87** [comment]
Hi @chadhamre it looks awesome I'll be putting this one on the next release with some small changes, like the contrast color, the thing is I want something that identifies the theme across the variations, however, I'm going to let people make accent color in settings, I think you propose this on an issue, thanks again for the help, if you think of something else let me know. 
p.d. do you know how to make accent color a setting? lol because I don't, thanks again.

**Comment by chadhamre** [comment]
Sounds great! I'll send you a note if I figure out how to make the accent color a setting. I think that's a great idea.

**Pull request merged**
